# Service Account for Azure Workload Identity
# This service account will be federated with an Azure AD Managed Identity
# to allow the pods to authenticate to Azure SQL using Azure AD

apiVersion: v1
kind: ServiceAccount
metadata:
  name: retail-monolith-sa
  namespace: retail-monolith
  annotations:
    azure.workload.identity/client-id: "568eab22-236f-46bb-970c-d953367834a5"
    azure.workload.identity/tenant-id: "714deb98-bf8b-47eb-8625-7fff26845f87"
  labels:
    azure.workload.identity/use: "true"

